### ISSUE TITLE
Initial Submit Not Working

### ISSUE THREAD

**Issue by cdomkokao** [formvalidation/formvalidation#1352] opened 2015-01-14 22:13 UTC
When I initially submit a page that has validations but that aren't required the form shows green outlines around the fields that they are successful but doesn't post the form.  I have traced the problem to the following code:

    .on('submit.bv', function(e) {
        e.preventDefault();
        that.validate();
    })

This code is validating the form when the submit button is first clicked but when all of the fields are successful this is causing the form to not actually post.  I have to put a value in one of the validated fields and then remove the value in order for the form to post.

If I comment out this piece of code the form submits just fine and stops submitting when there are errors.  The problem is that there are some screens that have a required field and I do want this validation to happen in those situations so I need those pages to validate on the first submit.  Without this code this doesn't happen.  I tried to write my own code to account for this but it isn't working.  I tried to put in the following (I have the vRequired css class on required fields:

    .on('submit.bv', function(e) {
        $(this).find('.vRequired').each(function(){
            e.preventDefault();
            that.validate();
        });
    })

This check worked for seeing if there was a required field in the form but the code fails.

Do you know how to solve this?  Could I get some help?

**Comment by cdomkokao** [comment] 2015-01-20 18:40
So I upgraded to the latest FV code and I am still having a problem with this.  When I click the submit button without touching the form I still just get green fields that show that they are validated but I can't move on.  The form doesn't post the first time.  If I click on a field, make an error and then fix the error the form posts.

**Comment by nghuuphuoc** [comment] 2015-01-23 08:35
@cdomkokao 
Can you please create a [jsfiddle](http://jsfiddle.net/) for it?

**Comment by cdomkokao** [comment] 2015-01-26 21:47
Here you go.  I can't submit the form without submitting and then changing something in the field and then submitting a second time.  It will highlight the field in green when I just submit but it still won't let me post.

http://jsfiddle.net/06wjguvw/3/

**Comment by nghuuphuoc** [comment] 2015-01-27 00:58
@cdomkokao 
The problem is that the submit button uses ```name="submit"```. It's been warned at the [Name conflict](http://formvalidation.io/getting-started/#name-conflict) section.

Here is working fiddle that doesn't use ```submit``` for name attribute of submit button:
http://jsfiddle.net/06wjguvw/5/

**Comment by cdomkokao** [comment] 2015-01-27 02:20
Holy crap... I spent a lot of time debugging and looking for the problem with this and that was a quick, easy fix.  Wow.  Thank you.

**Comment by nghuuphuoc** [comment] 2015-01-27 02:30
That's why I often ask for a fiddle.
It is more easy for us to find out the reason, right? :)

You can close the issue.

On Tuesday, January 27, 2015, cdomkokao <notifications@github.com> wrote:

> Holy crap... I spent a lot of time debugging and looking for the problem
> with this and that was a quick, easy fix. Wow. Thank you.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/formvalidation/formvalidation/issues/1352#issuecomment-71579061>
> .
>


-- 
Phuoc Nguyen
Sent from my iPhone

**Closed** 2015-01-28 16:25 UTC
Labels: question
